fix: add documentation on substitution and shell variable expansion
ismaelgv/rnr pull request #38
Opened 2023-11-27 13:16 UTC by lucas-deangelis

As discussed in #37. I've kept the explanation in `.help()` short to avoid either weird formatting or having to switch it to `.long_help()`.

Using double quotes for the REPLACEMENT argument with capture group substitution in shells like Bash or zsh will not work as intended. For example, a "${1}" will be replaced by the content of the shell variable 1 before rnr can read them, resulting in no substitution.

2023-11-27 23:36 UTC, ismaelgv requested changes
Thanks for the contribution :wink:

2023-11-27 23:36 UTC, ismaelgv commented on README.md
> +```
```suggestion
__SHELL NOTE:__ In shells like Bash and zsh, make sure to wrap the `REPLACEMENT` pattern in single quotes. Otherwise, capture group indices will be replaced by expanded shell variables.
```
I think this note is fine, but I would remove the example since it may cause confusion. Other examples in the documentation are valid behavior.

2023-11-27 23:36 UTC, ismaelgv commented on src/app.rs
> +                .help("Expression replacement. Enclose in single quotes to prevent variable expansion")
Not sure about this, the use may actually want to use variable expansion, for example:

```sh
rnr -r '.txt' "${OTHER_EXT}" .
```

Maybe we can reword this to:
`Expression replacement (use single quotes for capture groups)`

2023-11-28 18:33 UTC, lucas-deangelis commented
Thanks for the review! I've made the two changes.

2023-11-28 18:57 UTC, ismaelgv commented on README.md
It seems that some changes were applied here, but this is not the global ToC of the document, just the examples ToC. I would revert this.

2023-11-28 21:12 UTC, lucas-deangelis commented on README.md
You're right, good catch and sorry about that. This should be fixed now.

2023-11-28 21:13 UTC, ismaelgv approved these changes

2023-11-28 21:14 UTC, merged